apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: syncsecretakv
  annotations:
    {{ if .Values.workloadIdentity.userAssignedClientId -}}
    azure.workload.identity/client-id: "{{ .Values.workloadIdentity.userAssignedClientId }}"
    {{- end }}
  name: syncsecretakv-controller-manager
  namespace: {{ .Values.namespace | default "syncsecretakv-system" }}