apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: syncsecretakv
    control-plane: controller-manager
  name: syncsecretakv-controller-manager-metrics-service
  namespace: {{ .Values.namespace | default "syncsecretakv-system" }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager