# permissions for end users to view clusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: syncsecretakv
    app.kubernetes.io/managed-by: kustomize
  name: api-clusterconfig-viewer-role
rules:
- apiGroups:
  - api.syncsecretakv.io
  resources:
  - clusterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.syncsecretakv.io
  resources:
  - clusterconfigs/status
  verbs:
  - get
