# permissions for end users to edit configs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: syncsecretakv
    app.kubernetes.io/managed-by: kustomize
  name: api-config-editor-role
rules:
- apiGroups:
  - api.syncsecretakv.io
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.syncsecretakv.io
  resources:
  - configs/status
  verbs:
  - get
