# permissions for end users to view syncsecretakvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: syncsecretakv
    app.kubernetes.io/managed-by: kustomize
  name: api-syncsecretakv-viewer-role
rules:
- apiGroups:
  - api.syncsecretakv.io
  resources:
  - syncsecretakvs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.syncsecretakv.io
  resources:
  - syncsecretakvs/status
  verbs:
  - get
