---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.syncsecretakv.io
  resources:
  - configs
  - syncsecretakvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.syncsecretakv.io
  resources:
  - configs/finalizers
  - syncsecretakvs/finalizers
  verbs:
  - update
- apiGroups:
  - api.syncsecretakv.io
  resources:
  - configs/status
  - syncsecretakvs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
